name: Mantener Supabase Activo

on:
  schedule:
    # Se ejecuta a las 00:00 cada 3 días
    - cron: '0 0 */3 * *'
  workflow_dispatch: # Permite ejecución manual

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer consulta a la API de Supabase
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/actividades1?select=id&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
